### ISSUE TITLE
Crash on D-PAD input while doing the dash inputs (PS4 Controller)

### ISSUE THREAD

**Issue by philg-dev** [Hyphen-ated/HoverPractice#3]
Hi there,

so I've tried your neat hover practice tool the other day and stumbled upon a crash.

![hover_crash](https://user-images.githubusercontent.com/6079229/34314479-5a133400-e774-11e7-97d6-e6c3c6d31d0b.PNG)

I get the crash when I try to use the D-PAD while doing the dash inputs (in my case the circle button on the PS4 controller).
Due to your nice little simulated preview with the moldorm2 hole I was like "okay, let's try to actually make it over this gap" and tried to walk down while hovering (or trying to do so at least).

I bet there's an easy fix for that, but I have no clue about python, just wanted you to know about it.
(also fatmanspanda pushed me to report the error, and I guess he's right - I should)

Kind regards,

apex82

**Comment by Hyphen-ated** [comment]
Thanks for the report. I just released a fix
