### ISSUE TITLE
Keyboard keys not working

### ISSUE THREAD

**Issue by sepulchre** [Hyphen-ated/HoverPractice#4]
I guess this only works for controllers/joypads and not for the keys of a keyboard?

**Comment by Hyphen-ated** [comment]
That's right.
It wouldn't be all that much work to make it so the program can read your keyboard, but I'm not sure if it would be worth it. I'm kinda skeptical that a human can perform successful hover inputs on a keyboard.

**Comment by sepulchre** [comment]
Well, I'm playing on keyboard and wanted to check out the hovering trick.
So from what I understand you are only allowed to let the button away for 1 frame, that means you have to tap it constantly.
If the trick works on controller buttons, I don't see why it shouldn't work on a keyboard?
Maybe it doesn't but that is why I wanted to check out your nice tool. Sadly not suitable for keyboards.

Btw. are macros allowed in the ALTTP Rando community? One could program a macro easily.

**Comment by Hyphen-ated** [comment]
The technique used on controller buttons involves scraping across the button with two fingers, so that it's released by the first finger for a very short period of time before being pressed by the second finger. I don't think this would work on a keyboard.

Macros are of course not allowed.

**Comment by Hyphen-ated** [comment]
This turned out to be very easy, so I added it and made a release.

**Comment by Hyphen-ated** [comment]
If you ever successfully hover with your keyboard, please do tell me about it
